### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by yashodhank** [rikhoffbauer/loaf-crack#2]
```
❯ brew reinstall --cask loaf
==> Downloading https://github.com/philipardeljan/getloaf/releases/download/v1.1.18/loaf.dmg
Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/52e7f5c5ddfddf142c0d278180f4b84e155b1ab3d5348c55eba2596761ccb2a6--loaf.dmg
==> Uninstalling Cask loaf
==> Purging files for version 1.1.18 of Cask loaf
==> Installing Cask loaf
==> Moving App 'Loaf.app' to '/Applications/Loaf.app'
🍺  loaf was successfully installed!
❯ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/rikhoffbauer/loaf-crack/master/patch.bash)"
(node:2451) ExperimentalWarning: The fs.promises API is experimental
(node:2452) ExperimentalWarning: The fs.promises API is experimental
sed: 1: "/var/folders/9m/g_913sb ...": invalid command code f
(node:2448) ExperimentalWarning: The fs.promises API is experimental
(node:2456) ExperimentalWarning: The fs.promises API is experimental

```
Failed to activate

**Comment by rikhoffbauer** [comment]
> ```
> ❯ brew reinstall --cask loaf
> ==> Downloading https://github.com/philipardeljan/getloaf/releases/download/v1.1.18/loaf.dmg
> Already downloaded: /Users/xxx/Library/Caches/Homebrew/downloads/52e7f5c5ddfddf142c0d278180f4b84e155b1ab3d5348c55eba2596761ccb2a6--loaf.dmg
> ==> Uninstalling Cask loaf
> ==> Purging files for version 1.1.18 of Cask loaf
> ==> Installing Cask loaf
> ==> Moving App 'Loaf.app' to '/Applications/Loaf.app'
> 🍺  loaf was successfully installed!
> ❯ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/rikhoffbauer/loaf-crack/master/patch.bash)"
> (node:2451) ExperimentalWarning: The fs.promises API is experimental
> (node:2452) ExperimentalWarning: The fs.promises API is experimental
> sed: 1: "/var/folders/9m/g_913sb ...": invalid command code f
> (node:2448) ExperimentalWarning: The fs.promises API is experimental
> (node:2456) ExperimentalWarning: The fs.promises API is experimental
> ```
> 
> Failed to activate

Hey, could you post the output of ```realpath `which sed` ``` for me? It might be caused by the difference between `GNU sed` and macOS `sed`.

**Comment by yashodhank** [comment]
Thank you my sed path and some other details
```
❯ which sed
/usr/bin/sed
❯ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 11.6.5
      Kernel Version: Darwin 20.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: xxxxx
      User Name: xxxxx
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: x

```

**Comment by rikhoffbauer** [comment]
> Thank you my sed path and some other details
> 
> ```
> ❯ which sed
> /usr/bin/sed
> ❯ system_profiler SPSoftwareDataType
> Software:
> 
>     System Software Overview:
> 
>       System Version: macOS 11.6.5
>       Kernel Version: Darwin 20.6.0
>       Boot Volume: Macintosh HD
>       Boot Mode: Normal
>       Computer Name: xxxxx
>       User Name: xxxxx
>       Secure Virtual Memory: Enabled
>       System Integrity Protection: Enabled
>       Time since boot: x
> ```

Try installing gnu-sed using brew, make sure to update your `PATH` accordingly.

```
brew install gnu-sed
```

Follow the instructions printed upon installation completion:

```
$ brew install gnu-sed
  [...]
  GNU "sed" has been installed as "gsed".
  If you need to use it as "sed", you can add a "gnubin" directory
  to your PATH from your bashrc like:     
    PATH="$(brew --prefix)/opt/gnu-sed/libexec/gnubin:$PATH"
  [...]
```

Be sure to source your .bashrc/.zshrc or whatever you're using or open a new shell session.

Verify that running ``` realpath `which sed` ``` prints something similar to `/usr/local/Cellar/gnu-sed/4.8/bin/gsed`

**Comment by yashodhank** [comment]
it worked, trick is open app, let it update from within the loaf app then run patch, nodejs and npx should also be installed `brew install npm` before you run the path if in case it is not installed already. Thank you so much!
